### ISSUE TITLE
How are users/applications intended to work with this protocol?

### ISSUE THREAD

**Issue by collincusce** [ethereum/beacon_chain#2]
Each shard seems to have its own address space. Does it have its own spend space as well? For non-validators, where does their source of value reside? Main chain? Do individuals stake into a shard like we would stake into a plasma chain? How are transactions intended to be sent? To the shard, I assume, which has individual contracts, no? So if I was to send a transaction on this system, would I bind my application to a default shard? How can I balance load across multiple shards? Is it even necessary for contracts to have a separate chain? Can they all reside on main or beacon chain? Really the EVM just needs to read the code, ya? It can technically execute it under whatever context it wants. State needs sharding, not contracts.

**Comment by djrtwo** [comment]
There is no VM in the beacon chain. All value and computation (other than concerning organizing validators) will occur in the shards. This current spec does not handle the details around cross shard communication and load balancing. That should be discussed in http://ethresear.ch. 

The goal is for this complexity to be masked with higher level tools so that a user interacts with the sharded network in a very similar way they interact with a single non-sharded chain.

**Comment by collincusce** [comment]
Thanks!
